http:

  # Custom routers are listed here. For example when a remote service is needed
  routers:
    pihole:
      entryPoints:
        - https
      rule: 'Host(`pihole.<DOMAIN>.<TLD>`)'
      service: pihole
      tls:
        certResolver: letsencrypt


  # Remote services are listed here, for when Docker integration is not possible
  services:
    pihole:
      loadBalancer:
        servers:
          - url: http://192.168.2.34:81/


  ## MIDDLEWARES ##
  middlewares:
    local-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - 127.0.0.1/32 # localhost
          - 192.168.2.0/24 # LAN Subnet
          - 100.0.0.0/8 # Tailscale VPN
          - fd7a:115c:a1e0:ab12::/64 # Tailscale VPN

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "strict-origin-when-cross-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305