version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8085
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun
    network_mode: "service:gluetun"

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: bridge
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # <-- This needs to be the same as WEBUI_PORT from qBittorrent
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=<YOUR MULLVAD ID>
      - SERVER_CITIES=amsterdam
    restart: unless-stopped
